version: "3"
services:

  frontend:
    image: ${IMAGE_REPOSITORY}frontend:${TAG}
    networks:
      - docker-compose_default      
      
  backend:
    image: ${IMAGE_REPOSITORY}backend:${TAG}
    networks:
      - docker-compose_default
    environment:
      - ASPNETCORE_ENVIRONMENT=Development      
 
  reverse-proxy:
    image: ${IMAGE_REPOSITORY}reverse-proxy:${TAG} 
    ports:
      - ${REVERSE-PROXY_PORT}:80
    networks:
      - docker-compose_default      
      
networks:
  docker-compose_default:
    external: true      
        